server:
  port: ${port:8888}
  use-forward-headers: true
  tomcat:
    min-spare-threads: 20
    max-threads: 200
    max-http-header-size: 8192
    remote-ip-header: X-Forwarded-for
    protocol-header: X-Forwarded-Proto
    port-header: X-Forwarded-Port
    uri-encoding: UTF-8
  compression:
      enabled: true
      min-response-size: 1024
      mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
spring:
  profiles:
    active: ${@profileActive@:dev}
  application:
    name: spring-boot-seed-project
  # HTTP ENCODING
  servlet:
      multipart:
          max-file-size: 2MB
          max-request-size: 10MB
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  config: classpath:log4j2-spring.xml